version: '3'
services:
  api-herois:
    build: .
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb-heroes
      PORT: 4000
    depends_on:
      - mongodb-heroes
    link:
      - mongodb-heroes
  
  mongodb-heroes:
    image: mongo:3.5
    ports:
      - 27017:27017
