apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
spec:
  rules:
  - http:
      paths:
        - path: /
          backend: 
            serviceName: api-heroes-svc
            servicePort: 4000

  - host: mysite.com
    http: 
      paths:
        - path: /
          backend:
            serviceName: nginx
            servicePort: 80
